git:
  submodules: false
os: windows
include:
  - os: windows
    env: CC=CL.exe CXX=CL.exe
language: cpp
before_install:
install:
script:
- "./configure --with-boost=/tmp/extra --disable-binary"
- export PATH=${PATH}:$(pwd)/build/bin;make
after_success:
- "./CreateHeaderOnly"
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - Feature_BuildWindows
env:
    global:
    - secure: D5HPaNoM+cbZLcfqGvudY3irPd27q89npzr7jlaVjs1m782bii8XCKWwrwNQfge/7mtaY7RRDxdFJkRssVno5HaLItOg/MT6gBinyQGenPZXeh7ia2CYkeuiRhKrEfKAMhCcoe5RafYbCDWq8w5eZ6iMnRoFUiA66cWGlF1vBI4=
